POST http://localhost:3000/auth/signup


### signup 
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"ivar1456@gmail.com",
    "password":"ivarstha",
    "username":"Ravi Shrestha"
}

### signin 
POST http://localhost:3000/auth/signup
Content-Length: application/json

{
    "email": "ivar1456@gmail.com",
    "password":"ivarstha"
}

### create role
POST http://localhost:3000/role/create
Content-Type: application/json

{
    "name":"producer"
}

### get roles
GET  http://localhost:3000/role/getAllRoles

### delete roles
DELETE http://localhost:3000/role/delete/15

### create artist
POST http://localhost:3000/artist/create
Content-Type: application/json

{
    "artist_name":"Tom hardy",
    "DOB":"1970-1-5",
    "profile_summary":"Tom Cruise is a well established actor in hollywood. He is the best action hero in hollywood/",
    "roleIds":[1,2]
}

### get Single Artist
GET http://localhost:3000/artist/3


### get all Artist
GET http://localhost:3000/artist/getAll


### update artist
PUT http://localhost:3000/artist/update/3
Content-Type: application/json

{
    "artist_name":"William Jackson",
    "height": 132.0
}

### delete artist
DELETE http://localhost:3000/artist/delete/6

