POST http://localhost:3000/auth/signup


### signup 
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"ivar1456@gmail.com",
    "password":"ivarstha",
    "username":"Ravi Shrestha"
}

### signin 
POST http://localhost:3000/auth/signup
Content-Length: application/json

{
    "email": "ivar1456@gmail.com",
    "password":"ivarstha"
}

### create role
POST http://localhost:3000/role/create
Content-Type: application/json

{
    "name":"producer"
}

### get roles
GET  http://localhost:3000/role/getAllRoles