POST http://localhost:3000/auth/signup


### signup 
POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"ivarstha@gmail.com",
    "password":"ivarstha",
    "username":"Ravi Shrestha"
}

### signin 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"ivarstha@gmail.com",
    "password":"ivarstha"
}

### create role
POST http://localhost:3000/role/create
Content-Type: application/json

{
    "name":"cinematographer"
}

### get roles
GET  http://localhost:3000/role/getAllRoles

### delete roles
DELETE http://localhost:3000/role/delete/15

### create artist
POST http://localhost:3000/artist/create
Content-Type: application/json


{
    "artist_name":"Tom hundered",
    "DOB":"1970-1-5",
    "profile_summary":"Tom Cruise is a well established actor in hollywood. He is the best action hero in hollywood/",
    "roleIds":[1,2]
}

### get Single Artist
GET http://localhost:3000/artist/3


### get all Artist
GET http://localhost:3000/artist/getAll


### update artist
PUT http://localhost:3000/artist/update/3
Content-Type: application/json

{
    "artist_name":"William Jackson",
    "height": 132.0
}

### delete artist
DELETE http://localhost:3000/artist/delete/2


### create genre
POST http://localhost:3000/genre/create
Content-Type: application/json

{
    "genre_name":"Anime"
}

### get all genres
GET http://localhost:3000/genre/getAllGenre

### update genre by id
PUT http://localhost:3000/genre/update/1
Content-Type: application/json

{
    "genre_name": "Drama"
}

### delete genre by id
DELETE  http://localhost:3000/genre/delete/1

### get all movie
GET  http://localhost:3000/movie/getMovies

### delete movie by id
DELETE http://localhost:3000/movie/delete/1


### user rate a movie 
POST http://localhost:3000/rating/create

### delete image by id
DELETE  http://localhost:3000/gallery/image/1

### create rating
POST http://localhost:3000/rating/create/movie/111
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJpdmFyc3RoYUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjE3MjI0NCwiZXhwIjoxNzIzMDM2MjQ0fQ.-F5O1Z1NG4f0QoSmxUrmRtaQlKLLksNcRzFUQzRBQ5E

{
    "rate":5
}

### update user rating on movie
PUT  http://localhost:3000/rating/update/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJpdmFyc3RoYUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjE3MjI0NCwiZXhwIjoxNzIzMDM2MjQ0fQ.-F5O1Z1NG4f0QoSmxUrmRtaQlKLLksNcRzFUQzRBQ5E

{
    "rate":7
}

### get all user ratings
GET http://localhost:3000/rate/user/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJpdmFyc3RoYUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjE3MjI0NCwiZXhwIjoxNzIzMDM2MjQ0fQ.-F5O1Z1NG4f0QoSmxUrmRtaQlKLLksNcRzFUQzRBQ5E


### add movie to user watchlist
POST  http://localhost:3000/user/watchlist/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJpdmFyc3RoYUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjE3MjI0NCwiZXhwIjoxNzIzMDM2MjQ0fQ.-F5O1Z1NG4f0QoSmxUrmRtaQlKLLksNcRzFUQzRBQ5E
Content-Type: application/json

{
    "movie_id":2
}

### fetch user watchlist 
GET   http://localhost:3000/user/watchlist/fetchall/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJpdmFyc3RoYUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjE3MjI0NCwiZXhwIjoxNzIzMDM2MjQ0fQ.-F5O1Z1NG4f0QoSmxUrmRtaQlKLLksNcRzFUQzRBQ5E

### remove movie from user watch list
DELETE  http://localhost:3000/user/watchlist/remove/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJpdmFyc3RoYUBnbWFpbC5jb20iLCJyb2xlIjoiVVNFUiIsImlhdCI6MTcyMjE3MjI0NCwiZXhwIjoxNzIzMDM2MjQ0fQ.-F5O1Z1NG4f0QoSmxUrmRtaQlKLLksNcRzFUQzRBQ5E
